import type { Product } from './types'

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`

// The agent shops the "audio" category by default (matches the demo brief),
// but the store carries more so search and the homepage feel like a real shop.
export const catalog: Product[] = [
  {
    id: 'aria-anc',
    name: 'Aria ANC Headphones',
    brand: 'Aria',
    category: 'audio',
    price: 8499,
    rating: 4.7,
    ratingCount: 3241,
    deliveryDays: 1,
    image: img('1505740420928-5e560c06d30e'),
    features: ['anc', 'wireless', 'multipoint', '40h battery'],
    blurb: 'Adaptive noise cancellation, 40-hour battery, and balanced sound for travel and calls.',
  },
  {
    id: 'nimbus-quiet',
    name: 'Nimbus Quiet Pro',
    brand: 'Nimbus',
    category: 'audio',
    price: 7299,
    rating: 4.2,
    ratingCount: 1187,
    deliveryDays: 3,
    image: img('1484704849700-f032a568e944'),
    features: ['anc', 'wireless', '30h battery'],
    blurb: 'Hybrid noise cancellation with a warm signature, at a friendly price.',
  },
  {
    id: 'studio-one',
    name: 'Studio One Wireless',
    brand: 'Studio',
    category: 'audio',
    price: 11249,
    rating: 4.8,
    ratingCount: 5620,
    deliveryDays: 1,
    image: img('1546435770-a3e426bf472b'),
    features: ['anc', 'wireless', 'multipoint', 'hi-res'],
    blurb: 'Reference-grade sound and best-in-class ANC — the audiophile pick.',
  },
  {
    id: 'volt-air',
    name: 'Volt Air Buds',
    brand: 'Volt',
    category: 'audio',
    price: 4499,
    rating: 4.0,
    ratingCount: 902,
    deliveryDays: 2,
    image: img('1590658268037-6bf12165a8df'),
    features: ['wireless', '24h battery'],
    blurb: 'Lightweight everyday earbuds — no ANC, but great value.',
  },
  {
    id: 'echo-frame',
    name: 'Echo Frame Over-Ear',
    brand: 'Echo',
    category: 'audio',
    price: 9799,
    rating: 3.9,
    ratingCount: 431,
    deliveryDays: 5,
    image: img('1577174881658-0f30ed549adc'),
    features: ['anc', 'wireless'],
    blurb: 'Bold styling and strong bass, but ships from a slower warehouse.',
  },
  {
    id: 'pulse-lite',
    name: 'Pulse Lite On-Ear',
    brand: 'Pulse',
    category: 'audio',
    price: 5299,
    rating: 4.4,
    ratingCount: 2044,
    deliveryDays: 2,
    image: img('1524678606370-a47ad25cb82a'),
    features: ['wireless', 'foldable', '35h battery'],
    blurb: 'Compact, foldable, long battery — but skips active noise cancellation.',
  },
  // Other categories: populate the storefront so nothing looks empty.
  {
    id: 'lumen-14',
    name: 'Lumen 14 Ultrabook',
    brand: 'Lumen',
    category: 'laptops',
    price: 61990,
    rating: 4.6,
    ratingCount: 812,
    deliveryDays: 2,
    image: img('1496181133206-80ce9b88a853'),
    features: ['16gb', 'oled', '1.1kg'],
    blurb: 'Featherweight OLED ultrabook for work anywhere.',
  },
  {
    id: 'forge-15',
    name: 'Forge 15 Creator',
    brand: 'Forge',
    category: 'laptops',
    price: 84990,
    rating: 4.5,
    ratingCount: 610,
    deliveryDays: 3,
    image: img('1517336714731-489689fd1ca8'),
    features: ['32gb', 'rtx', '2.1kg'],
    blurb: 'Discrete graphics and a colour-accurate panel for creators.',
  },
  {
    id: 'orbit-watch',
    name: 'Orbit Active Watch',
    brand: 'Orbit',
    category: 'wearables',
    price: 12499,
    rating: 4.3,
    ratingCount: 1533,
    deliveryDays: 1,
    image: img('1523275335684-37898b6baf30'),
    features: ['gps', 'amoled', 'spo2'],
    blurb: 'Bright AMOLED, built-in GPS, and a week of battery.',
  },
  {
    id: 'pace-band',
    name: 'Pace Band 3',
    brand: 'Pace',
    category: 'wearables',
    price: 3299,
    rating: 4.1,
    ratingCount: 4120,
    deliveryDays: 2,
    image: img('1579586337278-3befd40fd17a'),
    features: ['heart rate', 'sleep'],
    blurb: 'A no-fuss fitness band that just works.',
  },
  {
    id: 'boom-360',
    name: 'Boom 360 Speaker',
    brand: 'Boom',
    category: 'audio',
    price: 6799,
    rating: 4.5,
    ratingCount: 2890,
    deliveryDays: 2,
    image: img('1608043152269-423dbba4e7e1'),
    features: ['wireless', 'ip67', '20h battery'],
    blurb: 'Room-filling 360° sound, fully waterproof.',
  },
  {
    id: 'nova-pods',
    name: 'Nova Pods Mini',
    brand: 'Nova',
    category: 'audio',
    price: 3599,
    rating: 3.7,
    ratingCount: 356,
    deliveryDays: 4,
    image: img('1590658268037-6bf12165a8df'),
    features: ['wireless'],
    blurb: 'Tiny true-wireless buds for casual listening.',
  },
]

export const featuredIds = ['aria-anc', 'studio-one', 'orbit-watch', 'lumen-14', 'boom-360', 'pace-band']

export function byCategory(category: string) {
  return catalog.filter((p) => p.category === category)
}

export function getProduct(id: string) {
  return catalog.find((p) => p.id === id)
}

export const featureLabels: Record<string, string> = {
  anc: 'Active noise cancellation',
  wireless: 'Wireless',
  multipoint: 'Multipoint pairing',
  'hi-res': 'Hi-res audio',
  foldable: 'Foldable',
  ip67: 'Waterproof',
}
